name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./templates/aspnet6.onion
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./templates/aspnet6.onion/src/MyTemplate.API
    - name: Unittest Domain Layer
      run: dotnet test MyTemplate.Domain.UnitTests.csproj --no-restore --verbosity normal
      working-directory: templates/aspnet6.onion/tests/MyTemplate.Domain.UnitTests
    - name: Unittest Application Layer
      run: dotnet test MyTemplate.Application.UnitTests.csproj --no-restore --verbosity normal
      working-directory: templates/aspnet6.onion/tests/MyTemplate.Application.UnitTests
    - name: Componenttest Application
      run: dotnet test MyTemplate.Application.ComponentTests.csproj --no-restore --verbosity normal
      working-directory: templates/aspnet6.onion/tests/MyTemplate.Application.ComponentTests
